/* autogenerated by Processing revision 1293 on 2024-02-27 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import oscP5.*;
import netP5.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Vector_rotacion extends PApplet {




OscP5 oscP5;
float rotX, rotY, rotZ;

public void setup() {
  /* size commented out by preprocessor */;
  oscP5 = new OscP5(this, 12000); // Puerto para recibir mensajes OSC
  rotX = rotY = rotZ = 0;
  
  
}

public void draw() {
  background(255);
  lights();
  translate(width/2, height/2, 0);
  
  //titulos
  
  
  // Muestra los valores del vector rotacion  en la esquina superior izquierda
  fill(0);
  textSize(20);
  text("Sensor VECTOR de ROTACI\u00d3N de PD", -200, -200);
  textSize(14);
   fill(230, 0, 0); // Color rojo
  text("Ubicar el Smartphone con el display hacia arriba para calibrar", -200, -180);
  
  
  textSize(14);
   fill(40, 0, 0); // Color rojo
  text("Tesis Doctoral - Posada Juen Pablo Posada A.", -200, 180);
 
  textSize(11);
   fill(0, 0, 0); // Color rojo
  text("Dise\u00f1o y desarrollo de Sistemas MMHCI para muica mixta y electroacustica P.", -200, 200);
  
  
  text("rotX: " + rotX, -180, -60);
  text("rotY: " + rotY, -180, -40);
  text("rotZ: " + rotZ, -180, -20);
  
  
  rotateX(rotX);
  rotateY(rotY);
  rotateZ(rotZ);
  
  // Dibujar las l\u00edneas de los ejes x, y, z
  fill(100);
  ellipse(-150, 0, 30, 30);
  strokeWeight(2);
  stroke(255, 0, 0); // Eje x en rojo
  line(-50, 0, 0, 50, 0, 0);
  stroke(0, 255, 0); // Eje y en verde
  line(0, -50, 0, 0, 50, 0);
  stroke(0, 0, 255); // Eje z en azul
  line(0, 0, -50, 0, 0, 50);
  
  
  drawCube();
  
   // Dibujar la palabra "front" en la cara frontal del cubo
  pushMatrix();
  translate(0, 0, 50); // Mover al frente del cubo
  fill(0); // Color negro para el texto
  textSize(12); // Tama\u00f1o de la fuente
  text("Costado", -22, -20); // Posicionar el texto en la parte superior izquierda de la cara frontal
   text("frontal", -18, 0);
    text("Smartphone", -29, 20);
  popMatrix();
  
   // Dibujar la palabra "superior" en la cara superior del cubo
  pushMatrix();
  translate(0, -50, 0); // Mover a la cara superior del cubo
  fill(0); // Color negro para el texto
  textSize(18); // Tama\u00f1o de la fuente
  text("DISPLAY", -35, -10); // Posicionar y dibujar el texto
  popMatrix();
  
  // Dibujar la palabra "tapa trasera" en la cara inferior del cubo
  pushMatrix();
  translate(0, 50, 0); // Mover a la cara inferior del cubo
  fill(0); // Color negro para el texto
  textSize(18); // Tama\u00f1o de la fuente
 // text("tapa trasera", -45, -5); // Posicionar y dibujar el texto
   text("tapa trasera", -45, 20);
  popMatrix();
  
    // diduja GRll 3d
   //drawGrid(10, width);
  
  
  
  
}

public void drawCube() {
  stroke(0);
  fill(150);
  box(100);
  
   // Dibujar l\u00ednea roja que atraviesa el cubo por el eje X
  stroke(255, 0, 0);
  line(-150, 0, 0, 150, 0, 0);
  
   // Dibujar l\u00ednea azul que atraviesa el cubo por el eje Y
  stroke(0, 0, 255); // Color azul
  line(0, -150, 0, 0, 150, 0); // Desde el centro del cubo hacia arriba y abajo
}

public void oscEvent(OscMessage theOscMessage) {
  if (theOscMessage.checkAddrPattern("/rotationX")) {
    rotX = theOscMessage.get(0).floatValue();
  } else if (theOscMessage.checkAddrPattern("/rotationY")) {
    rotY = theOscMessage.get(0).floatValue();
  } else if (theOscMessage.checkAddrPattern("/rotationZ")) {
    rotZ = theOscMessage.get(0).floatValue();
  }
}


public void drawHorizonGrid() {
  stroke(200);
  for (int i = -5; i <= 5; i++) {
    line(-250, i * 50, 0, 250, i * 50, 0); // L\u00edneas horizontales
    line(i * 50, -250, 0, i * 50, 250, 0); // L\u00edneas verticales
  }
}


public void drawGrid(float spacing, float size) {
  pushMatrix();
  stroke(210);
  strokeWeight(1);
  for (float i = -size/2; i <= size/2; i += spacing) {
    line(i, -size/2, 0, i, size/2, 0);
    line(-size/2, i, 0, size/2, i, 0);
  }
  for (float i = -size/2; i <= size/2; i += spacing) {
    line(0, -size/2, i, 0, size/2, i);
  }
  popMatrix();
}


  public void settings() { size(600, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Vector_rotacion" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
